import { Category } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Tenis & Sneakers', slug: 'tenis-sneakers' },
  { id: 'cat-2', name: 'Perfumes & Fragancias', slug: 'perfumes-fragancias' },
  { id: 'cat-3', name: 'T-Shirts & Camisetas', slug: 't-shirts-camisetas' },
  { id: 'cat-4', name: 'Pantalones & Jeans', slug: 'pantalones-jeans' },
  { id: 'cat-5', name: 'Relojes & Accesorios', slug: 'relojes-accesorios' },
  { id: 'cat-6', name: 'Gorras & Caps', slug: 'gorras-caps' },
  { id: 'cat-7', name: 'Camisas & Polos', slug: 'camisas-polos' },
  { id: 'cat-8', name: 'Chaquetas & Hoodies', slug: 'chaquetas-hoodies' },
];

export const INITIAL_PRODUCTS: any[] = [
  {
    id: 'prod-1',
    name: 'Nike Air Jordan 1 Retro High OG',
    slug: 'nike-air-jordan-1-retro-high-og',
    sku: 'NK-AJ1-OG',
    basePrice: 180.0,
    compareAtPrice: 210.0,
    status: 'PUBLISHED',
    category: { id: 'cat-1', name: 'Tenis & Sneakers', slug: 'tenis-sneakers' },
    brand: { id: 'b-1', name: 'Nike', slug: 'nike' },
    images: [{ id: 'img-1', url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=600', isMain: true, displayOrder: 0 }],
    variants: [
      { id: 'v1', sku: 'NK-AJ1-CHI-40', title: 'Chicago Red / Talla 40', price: 180.0, stock: 35, attributes: { Color: 'Chicago Red', Talla: '40' } },
      { id: 'v2', sku: 'NK-AJ1-CHI-42', title: 'Chicago Red / Talla 42', price: 180.0, stock: 24, attributes: { Color: 'Chicago Red', Talla: '42' } },
      { id: 'v3', sku: 'NK-AJ1-BLK-41', title: 'Shadow Black / Talla 41', price: 185.0, stock: 19, attributes: { Color: 'Shadow Black', Talla: '41' } },
      { id: 'v4', sku: 'NK-AJ1-BLK-42', title: 'Shadow Black / Talla 42', price: 185.0, stock: 18, attributes: { Color: 'Shadow Black', Talla: '42' } },
    ],
  },
  {
    id: 'prod-2',
    name: 'Adidas Ultraboost Light Running',
    slug: 'adidas-ultraboost-light-running',
    sku: 'AD-UB-LIGHT',
    basePrice: 149.99,
    compareAtPrice: 190.0,
    status: 'PUBLISHED',
    category: { id: 'cat-1', name: 'Tenis & Sneakers', slug: 'tenis-sneakers' },
    brand: { id: 'b-2', name: 'Adidas', slug: 'adidas' },
    images: [{ id: 'img-2', url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=600', isMain: true, displayOrder: 0 }],
    variants: [
      { id: 'v5', sku: 'AD-UB-WHT-40', title: 'Triple White / Talla 40', price: 149.99, stock: 25, attributes: { Color: 'Triple White', Talla: '40' } },
      { id: 'v6', sku: 'AD-UB-WHT-41', title: 'Triple White / Talla 41', price: 149.99, stock: 40, attributes: { Color: 'Triple White', Talla: '41' } },
      { id: 'v7', sku: 'AD-UB-BLK-42', title: 'Core Black / Talla 42', price: 155.0, stock: 30, attributes: { Color: 'Core Black', Talla: '42' } },
    ],
  },
  {
    id: 'prod-3',
    name: 'Dior Sauvage Eau de Parfum',
    slug: 'dior-sauvage-eau-de-parfum-100ml',
    sku: 'DIOR-SV-100',
    basePrice: 135.0,
    compareAtPrice: 160.0,
    status: 'PUBLISHED',
    category: { id: 'cat-2', name: 'Perfumes & Fragancias', slug: 'perfumes-fragancias' },
    brand: { id: 'b-3', name: 'Dior', slug: 'dior' },
    images: [{ id: 'img-3', url: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?q=80&w=600', isMain: true, displayOrder: 0 }],
    variants: [
      { id: 'v8', sku: 'DIOR-SV-EDP-100ML', title: 'Frasco 100ml / EDP', price: 135.0, stock: 45, attributes: { Capacidad: '100ml', Tipo: 'EDP' } },
      { id: 'v9', sku: 'DIOR-SV-EDP-200ML', title: 'Frasco 200ml / Jumbo', price: 195.0, stock: 20, attributes: { Capacidad: '200ml', Tipo: 'Jumbo' } },
    ],
  },
  {
    id: 'prod-4',
    name: 'Camiseta Casual Heavy Cotton Oversize',
    slug: 'camiseta-casual-heavy-cotton-oversize',
    sku: 'TS-OVR-HVY',
    basePrice: 22.5,
    compareAtPrice: 35.0,
    status: 'PUBLISHED',
    category: { id: 'cat-3', name: 'T-Shirts & Camisetas', slug: 't-shirts-camisetas' },
    brand: { id: 'b-4', name: 'Zara Man', slug: 'zara-man' },
    images: [{ id: 'img-4', url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=600', isMain: true, displayOrder: 0 }],
    variants: [
      { id: 'v10', sku: 'TS-OVR-WHT-S', title: 'Blanco Crudo / Talla S', price: 22.5, stock: 40, attributes: { Color: 'Blanco Crudo', Talla: 'S' } },
      { id: 'v11', sku: 'TS-OVR-WHT-M', title: 'Blanco Crudo / Talla M', price: 22.5, stock: 65, attributes: { Color: 'Blanco Crudo', Talla: 'M' } },
      { id: 'v12', sku: 'TS-OVR-BLK-L', title: 'Negro Lavado / Talla L', price: 22.5, stock: 38, attributes: { Color: 'Negro Lavado', Talla: 'L' } },
      { id: 'v13', sku: 'TS-OVR-BLK-XL', title: 'Negro Lavado / Talla XL', price: 22.5, stock: 22, attributes: { Color: 'Negro Lavado', Talla: 'XL' } },
    ],
  },
  {
    id: 'prod-5',
    name: 'Jeans Ajustados Slim Fit Denim Stretch',
    slug: 'jeans-ajustados-slim-fit-denim-stretch',
    sku: 'JNS-SLIM-511',
    basePrice: 39.99,
    compareAtPrice: 59.99,
    status: 'PUBLISHED',
    category: { id: 'cat-4', name: 'Pantalones & Jeans', slug: 'pantalones-jeans' },
    brand: { id: 'b-5', name: 'Levi\'s', slug: 'levis' },
    images: [{ id: 'img-5', url: 'https://images.unsplash.com/photo-1542272604-780c96856592?q=80&w=600', isMain: true, displayOrder: 0 }],
    variants: [
      { id: 'v14', sku: 'JNS-SLIM-30', title: 'Azul Medio / Talla 30', price: 39.99, stock: 30, attributes: { Color: 'Azul Medio', Talla: '30' } },
      { id: 'v15', sku: 'JNS-SLIM-32', title: 'Azul Medio / Talla 32', price: 39.99, stock: 48, attributes: { Color: 'Azul Medio', Talla: '32' } },
      { id: 'v16', sku: 'JNS-SLIM-34', title: 'Negro Denim / Talla 34', price: 42.0, stock: 25, attributes: { Color: 'Negro Denim', Talla: '34' } },
    ],
  },
  {
    id: 'prod-6',
    name: 'Reloj Cronógrafo Acero Inoxidable Black Dial',
    slug: 'reloj-cronografo-acero-inoxidable-black-dial',
    sku: 'RLJ-CRN-BLK',
    basePrice: 89.0,
    compareAtPrice: 130.0,
    status: 'PUBLISHED',
    category: { id: 'cat-5', name: 'Relojes & Accesorios', slug: 'relojes-accesorios' },
    brand: { id: 'b-6', name: 'Casio / G-Shock', slug: 'casio-g-shock' },
    images: [{ id: 'img-6', url: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=600', isMain: true, displayOrder: 0 }],
    variants: [
      { id: 'v17', sku: 'RLJ-SLV-BLK', title: 'Plata / Esfera Negra', price: 89.0, stock: 25, attributes: { Correa: 'Plata', Esfera: 'Negra' } },
      { id: 'v18', sku: 'RLJ-MAT-BLK', title: 'Negro Mate / Esfera Carbón', price: 99.0, stock: 15, attributes: { Correa: 'Negro Mate', Esfera: 'Carbón' } },
    ],
  },
  {
    id: 'prod-7',
    name: 'Gorra New Era NY Yankees 59FIFTY Fitted',
    slug: 'gorra-new-era-ny-yankees-59fifty-fitted',
    sku: 'NE-NY-5950',
    basePrice: 38.0,
    compareAtPrice: 45.0,
    status: 'PUBLISHED',
    category: { id: 'cat-6', name: 'Gorras & Caps', slug: 'gorras-caps' },
    brand: { id: 'b-7', name: 'New Era', slug: 'new-era' },
    images: [{ id: 'img-7', url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?q=80&w=600', isMain: true, displayOrder: 0 }],
    variants: [
      { id: 'v19', sku: 'NE-NY-NAVY-714', title: 'Azul Navy / Talla 7 1/4', price: 38.0, stock: 30, attributes: { Color: 'Azul Navy', Talla: '7 1/4' } },
      { id: 'v20', sku: 'NE-NY-BLK-712', title: 'Black on Black / Talla 7 1/2', price: 40.0, stock: 22, attributes: { Color: 'Black on Black', Talla: '7 1/2' } },
      { id: 'v21', sku: 'NE-NY-GRN-738', title: 'Verde Militar / Talla 7 3/8', price: 38.0, stock: 18, attributes: { Color: 'Verde Militar', Talla: '7 3/8' } },
    ],
  },
];
